In [135]:
# Working with Missing Data in Pandas
# Missing Data can occur when no information is provided for one or more
# items or for a whole unit. Missing Data is a very big problem in a real-life scenarios.
# Missing Data can also refer to as NA(Not Available) values in pandas.
# In DataFrame sometimes many datasets simply arrive with missing data,
# either because it exists and was not collected or it never existed.
# For Example, Suppose different users being surveyed may choose not to share their income,
# some users may choose not to share the address in this way many datasets went missing.

# Dataset 1 : https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/ufo.csv

# Dataset 2 : https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv

In [136]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

ufo = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/ufo.csv')
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [137]:
ufo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             18215 non-null  object
 1   Colors Reported  2882 non-null   object
 2   Shape Reported   15597 non-null  object
 3   State            18241 non-null  object
 4   Time             18241 non-null  object
dtypes: object(5)
memory usage: 712.7+ KB

In [138]:
ufo.isnull().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64

In [139]:
# remove missing values
# dropna()

ufo.dropna().shape          # if missing value is a lot, use fillna() to fill missing value

(2486, 5)

In [140]:
# fillna()
# Fill NA/NaN values using the specified method
# for object dtype not for int or float

ufo['City'].fillna(value='CityNotMentioned',inplace=True)

ufo['Colors Reported'].fillna(value='ColorsNotFound',inplace=True)

ufo['Shape Reported'].fillna(value='ShapeNotFound',inplace=True)

In [141]:
ufo.isnull().sum()

City               0
Colors Reported    0
Shape Reported     0
State              0
Time               0
dtype: int64

In [142]:
ufo.head(10)

                   City Colors Reported Shape Reported State              Time
0                Ithaca  ColorsNotFound       TRIANGLE    NY    6/1/1930 22:00
1           Willingboro  ColorsNotFound          OTHER    NJ   6/30/1930 20:00
2               Holyoke  ColorsNotFound           OVAL    CO   2/15/1931 14:00
3               Abilene  ColorsNotFound           DISK    KS    6/1/1931 13:00
4  New York Worlds Fair  ColorsNotFound          LIGHT    NY   4/18/1933 19:00
5           Valley City  ColorsNotFound           DISK    ND   9/15/1934 15:30
6           Crater Lake  ColorsNotFound         CIRCLE    CA    6/15/1935 0:00
7                  Alma  ColorsNotFound           DISK    MI    7/15/1936 0:00
8               Eklutna  ColorsNotFound          CIGAR    AK  10/15/1936 17:00
9               Hubbard  ColorsNotFound       CYLINDER    OR    6/15/1937 0:00

In [143]:
data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          7 non-null      int64
 1   Name        7 non-null      object
 2   Marks       5 non-null      float64
 3   Percentage  3 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 356.0+ bytes

In [144]:
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [145]:
data.isnull().sum()

Id            0
Name          0
Marks         2
Percentage    4
dtype: int64

In [146]:
# fillna() for fill missing value for int/flooat dtype using backward and forward fill

data['Marks'].fillna(method='bfill',inplace=True)

data['Percentage'].fillna(method='ffill',inplace=True)

In [147]:
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0        78.0
2   3  Alex   12.0        67.0
3   4  Alex   12.0        67.0
4   5  Alex   54.0        67.0
5   6  Alex   54.0        67.0
6   7  Alex   65.0        66.0

In [148]:
# fill mising value by taking up a mean -- better approch

data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [149]:
mean_val_marks = data['Marks'].mean()

data['Marks'].fillna(value=mean_val_marks,inplace=True)  # kalau x nk guna mean value boleh letak (value=0,inplace=True)

data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex   46.4        67.0
3   4  Alex   12.0         NaN
4   5  Alex   46.4         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [150]:
mean_val_perc = data['Percentage'].mean()
mean_val_perc = round(mean_val_perc,1)   # kurangkan kpd 1 titik perpuluhan

data['Percentage'].fillna(value=mean_val_perc,inplace=True)

data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0        70.3
2   3  Alex   46.4        67.0
3   4  Alex   12.0        70.3
4   5  Alex   46.4        70.3
5   6  Alex   54.0        70.3
6   7  Alex   65.0        66.0

In [151]:
# Filling missing value using interpolate()

data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/sample11.csv')
data

   Id  Name  Marks  Percentage
0   1  Alex   78.0        78.0
1   2  Alex   23.0         NaN
2   3  Alex    NaN        67.0
3   4  Alex   12.0         NaN
4   5  Alex    NaN         NaN
5   6  Alex   54.0         NaN
6   7  Alex   65.0        66.0

In [152]:
data.interpolate()

   Id  Name  Marks  Percentage
0   1  Alex   78.0       78.00
1   2  Alex   23.0       72.50
2   3  Alex   17.5       67.00
3   4  Alex   12.0       66.75
4   5  Alex   33.0       66.50
5   6  Alex   54.0       66.25
6   7  Alex   65.0       66.00

In [153]:
# Remove Duplicate Records

# Handle Duplicate Data
# Dealing With Duplicate Data

# Create a DataFrame
data = {
      'StudentName': ['Mark', 'Ali', 'Bob', 'John', 'Johny', 'Mark'],
      'Score': [45, 65, 76, 44, 39, 45]
}
df = pd.DataFrame(data)
df

  StudentName  Score
0        Mark     45
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45

In [154]:
# check for duplicate records

print(df.duplicated().sum())

1

In [155]:
df[df.duplicated()]     # to print that duplicate records

  StudentName  Score
5        Mark     45

In [156]:
df[df['StudentName']== 'Mark']

  StudentName  Score
0        Mark     45
5        Mark     45

In [157]:
# dropping duplicates

df.drop_duplicates(inplace=True)

print(df.duplicated().sum())

0

In [158]:
df

  StudentName  Score
0        Mark     45
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39

In [159]:
# Create a DataFrame
data = {
      'StudentName': ['Mark', 'Ali', 'Bob', 'John', 'Johny', 'Mark'],
      'Score': [45, 65, 76, 44, 39, 45]
}
df = pd.DataFrame(data)
df

  StudentName  Score
0        Mark     45
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45

In [160]:
# dropping duplicates -- delete and keep last data

df.drop_duplicates(keep='last', inplace=True)

df

  StudentName  Score
1         Ali     65
2         Bob     76
3        John     44
4       Johny     39
5        Mark     45