In [1]:
# Pandas Data Science library

import numpy as np
import pandas as pd
print(pd.__version__)

2.2.2

In [2]:
# numpy --> array()
arr = np.array([10,20,30,40,50])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50]

In [6]:
# Pandas Series
# Series is 1D Labelled Array

s = pd.Series([10,20,30,40,50])
print(type(s))
print(s)
print(s.shape)

# In Numpy --> Only Numbers
# In Series --> Number + Labels(index)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int64
(5,)

In [17]:
info = pd.Series(['John',28,6700,'Klang'], index = ['Name','Age','Sal','City'])
print(info)
print()
print(info['Name'])       # indexing
print(info.get('City'))   # getting data values using get()
print(info.iloc[0])       # iloc -->index location

# Series is like a Dictionary + array combo

Name     John
Age        28
Sal      6700
City    Klang
dtype: object

John
Klang
John

In [18]:
# values property
# print only values

print(info.values)

['John' 28 6700 'Klang']

In [40]:
# Indexing Slicing And Using For Loop

s = pd.Series([100,200,300,400,500,600],index=['v1','v2','v3','v4','v5','v6'])
print(s)

# 100  200   300   400    500     600
# 0     1     2     3      4       5
# -6    -5    -4    -3     -2      -1
# v1     v2   v3     v4    v5      v6

# Indexing in Series can be done by using [] or iloc[] or loc[]
print('\nIndexing In Series')

print(s.iloc[0])    # for index numbers
print(s.loc['v5'])  # loc used for labels
print(s['v2'])      # [] used for labels
print(s.iloc[-1])

print('\nSlicing In Series')
print(s[1:4])         # 4 will be excluded --> stopIndex
print(s['v2':'v5'])   # if performing slicing using labels, the end label is included

v1    100
v2    200
v3    300
v4    400
v5    500
v6    600
dtype: int64

Indexing In Series
100
500
200
600

Slicing In Series
v2    200
v3    300
v4    400
dtype: int64
v2    200
v3    300
v4    400
v5    500
dtype: int64

In [50]:
# print only 100,400 and 500

print(s['v1'],s['v4'],s['v5'])
print()
print(s[['v1','v4','v5']])        # for specific information s[['','','',]]
print()
print(s[['v1','v4','v5']].values) # just want the values output

# Conditional Selection
print('\nConditional Selection')
print(s[s%3==0])

100 400 500

v1    100
v4    400
v5    500
dtype: int64

[100 400 500]

Conditional Selection
v3    300
v6    600
dtype: int64

In [51]:
# Using for loop
for i in s:
  print(i)

100
200
300
400
500
600

In [53]:
for k,v in s.items():
  print(k,v)

v1 100
v2 200
v3 300
v4 400
v5 500
v6 600

In [57]:
for i in enumerate(s):
  print(i)

(0, 100)
(1, 200)
(2, 300)
(3, 400)
(4, 500)
(5, 600)

In [65]:
# Pandas DataFrame
# it is used to display the information in a tabular fashion
# Pandas DataFrame is 2D Array

data = {
    'Name' : ['John', 'Alex', 'Smith'],
    'Dept' : ['IT', 'HR', 'MR'],
    'Sal' : [6700,5600,6000],
    'City': ['KL', 'JB','ML']
}

print(data)

{'Name': ['John', 'Alex', 'Smith'], 'Dept': ['IT', 'HR', 'MR'], 'Sal': [6700, 5600, 6000], 'City': ['KL', 'JB', 'ML']}

In [66]:
df = pd.DataFrame(data)
df

    Name Dept   Sal City
0   John   IT  6700   KL
1   Alex   HR  5600   JB
2  Smith   MR  6000   ML

In [67]:
print(df)

    Name Dept   Sal City
0   John   IT  6700   KL
1   Alex   HR  5600   JB
2  Smith   MR  6000   ML

In [68]:
print(df.shape)

(3, 4)

In [74]:
data = {
    'Calories' : [420, 380, 560],
    'Duration' : [56, 30, 75]
}
df = pd.DataFrame(data,index=['Day 1','Day 2','Day 3'])
df

       Calories  Duration
Day 1       420        56
Day 2       380        30
Day 3       560        75

In [75]:
df['Calories']    # get data under Column

Day 1    420
Day 2    380
Day 3    560
Name: Calories, dtype: int64

In [77]:
print(df['Calories'].values)

[420 380 560]

In [82]:
df.loc['Day 1']   # get data under Row

Calories    420
Duration     56
Name: Day 1, dtype: int64

In [79]:
df.loc[['Day 1', 'Day 3']]

       Calories  Duration
Day 1       420        56
Day 3       560        75

In [ ]:
# Using Pandas To Deal With Diff Diff File Formats
      # Read an excel file
      # Read an csv file
      # Read a txt file
      # Read json file
      # Upload Local Files
	    # Read a sql file

In [90]:
# Read an excel file
# read_excel()

data = pd.read_excel('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
data

,id,first_name,last_name,email,gender,ip_address
0,1,Merle,Draisey,mdraisey0@squarespace.com,Bigender,20.70.199.51
1,2,Casey,Sheach,csheach1@deviantart.com,Male,226.126.229.167
2,3,Darya,Leivers,dleivers2@imgur.com,Female,247.209.88.235
3,4,Fancie,Casebourne,fcasebourne3@g.co,Female,172.34.162.239
4,5,Jenilee,Vsanelli,jvsanelli4@fc2.com,Female,200.104.246.2
...,...,...,...,...,...,...
995,996,Lutero,Yurov,lyurovrn@un.org,Male,95.146.16.187
996,997,Verla,Peery,vpeeryro@com.com,Female,172.90.253.234
997,998,Fran,Langran,flangranrp@ft.com,Male,123.179.99.154
998,999,Gabbi,Cummins,gcumminsrq@jugem.jp,Female,190.13.174.159
999,1000,Gloriane,Marc,gmarcrr@businessweek.com,Female,139.87.192.32

In [91]:
# ExcelFile()
# in order to get the data from a different sheet in excel file

excelfile = pd.ExcelFile('https://raw.githubusercontent.com/yash240990/Python/master/sampleExcelData.xlsx')
excelfile.sheet_names

['data', 'Sheet2']

In [92]:
data = pd.read_excel(excelfile,'Sheet2')
data

   first_name    last_name                                 email
0       Merle      Draisey             mdraisey0@squarespace.com
1       Casey       Sheach               csheach1@deviantart.com
2       Darya      Leivers                   dleivers2@imgur.com
3      Fancie   Casebourne                     fcasebourne3@g.co
4     Jenilee     Vsanelli                    jvsanelli4@fc2.com
5    Charmian    Drinkhall       cdrinkhall5@theglobeandmail.com
6     Janessa       Kivell                 jkivell6@linkedin.com
7       Mirna       Heinsh                  mheinsh7@spotify.com
8       Darby          Lax                   dlax8@people.com.cn
9       Meryl        Riehm                 mriehm9@princeton.edu
10       Anne        Brody                    abrodya@sphinn.com
11       Puff    Langsbury             plangsburyb@canalblog.com
12       Tina      Gregoli                  tgregolic@sfgate.com
13     Barbie       Dahlen                     bdahlend@narod.ru
14     Andeee  Dobrovolski  adobrovolskie@networkadvertising.org
15    Ainsley       Friman                      afrimanf@irs.gov
16        Bil     Shalcros                 bshalcrosg@dion.ne.jp
17    Raimund     Outridge                   routridgeh@lulu.com
18     Whitby     Millward                    wmillwardi@ask.com
19        Rob      Boarder                       rboarderj@51.la
20      Nicky     Curthoys                    ncurthoysk@pbs.org

In [93]:
# CSV --> comma separated value
# read_csv()

data = pd.read_csv('https://raw.githubusercontent.com/yash240990/Python/master/Position_Salaries.csv')
data

            Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [96]:
# read a txt file
# read_csv('...',sep='\t')

data = pd.read_csv('https://raw.githubusercontent.com/yashy1626/ds_dataset/refs/heads/main/iris.txt',sep='\t')
data

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [100]:
# read a JSON file
# read_json()

data = pd.read_json('https://raw.githubusercontent.com/yash240990/Python/master/simple.json')
data

     id   name  math  physics  chemistry
0  A001    Tom    60       66         61
1  A002  James    89       76         51
2  A003  Jenny    79       90         78

In [101]:
# upload local files in Jupyter
'''
first upload file in jupyter home page

data = pd.read_csv('mydata.csv')
data

'''

"\nupload file in jupyter home page\n\ndata = pd.read_csv('mydata.csv')\ndata\n\n"

In [102]:
# upload local files in colab  --> in colab, need reupload every time when reopen colab

from google.colab import files
uploaded = files.upload()       # file selection wizard

Saving mydata.csv to mydata.csv

In [103]:
data = pd.read_csv('mydata.csv')
data

,id,first_name,last_name,email,gender,department,salary
0,1,Dougie,Iwanczyk,diwanczyk0@princeton.edu,Male,Training,6242
1,2,Evanne,Mills,emills1@prlog.org,Female,Business Development,3733
2,3,Zebulon,Filippone,zfilippone2@creativecommons.org,Male,Product Management,3216
3,4,Gert,Drynan,gdrynan3@gravatar.com,Female,Product Management,4534
4,5,Conney,Goodburn,cgoodburn4@topsy.com,Male,Engineering,5250
...,...,...,...,...,...,...,...
995,996,Salvatore,Lushey,slusheyrn@oracle.com,Male,Training,5214
996,997,Danika,Crowther,dcrowtherro@friendfeed.com,Female,Engineering,7974
997,998,Cathi,Smails,csmailsrp@yahoo.co.jp,Female,Marketing,6007
998,999,Arielle,Thorsen,athorsenrq@amazon.de,Female,Human Resources,3319
999,1000,Melisse,Kasman,mkasmanrr@wikimedia.org,Female,Support,6070